# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(recipes)
    library(workflows)
    library(xgboost)
}
b <- board_rsconnect("envvar", server = "https://colorado.rstudio.com/rsc")
v <- vetiver_pin_read(b, "sam.edwardes/bike_predict_xgboost_r", version = "55814")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
