---
title: "Bike Share Forecast"
output: html_document
params:
  station:
      label: "Station Name"
      value: "Eads St & 15th St S"
      input: select
      choices: !r pins::pin("https://colorado.rstudio.com/rsc/bike_station_info/", name = "stations"); pins::pin_get("stations")$name
  alert: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(blastula)
library(ggplot2)
library(httr)
pins::board_register_rsconnect(server = "https://colorado.rstudio.com/rsc/", 
                               account = Sys.getenv("CONNECT_ACCOUNT"),
                               key = Sys.getenv("CONNECT_API_KEY"))
stations <- pins::pin_get("alex.gold/bike_station_info", board = "rsconnect")

```

The forecast for bike availability at `r params$station`

```{r forecast}

id <-  stations$station_id[which(stations$name == params$station)]
res <- httr::GET("https://colorado.rstudio.com/rsc/bike_predict_api/pred",
                    query = list(station_id = id)) %>%
              httr::content() %>%
              purrr::map_df(tibble::as_tibble) %>% 
              mutate(times = as.POSIXct(times))

p <- ggplot(res, aes(times, pred)) + 
  geom_line() + 
  theme_minimal() + 
  labs(
    title = "Bike Availability", 
    y = "# of Predicted Bikes", 
    x = NULL
  ) + 
  scale_x_datetime(labels = function(x) format(x - 18000, "%H:%M")) +
  scale_y_continuous(labels = round)
p
```

Specifically, you can expect `r res$pred[1]` bike(s) available at `r res$times[1]`.

```{r}
if (res$pred[1] < params$alert) {
  attach_connect_email(
    email = render_connect_email("email-body.Rmd"),
    subject = sprintf("Warning: Only going to be %g bikes left at %s", res$pred[1], params$station)
  )
} else {
  suppress_scheduled_email()
}
```
