---
title: "Content Admin"
date: "`r Sys.time()`"
output: html_document
---

This purpose of this script is to programatically manage the deployed content on Rstudio Connect.

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(rsconnect)
library(connectapi)

# Establish a connection to RStudio connect.
client <- connect(
  server = Sys.getenv("CONNECT_SERVER"),
  api_key = Sys.getenv("CONNECT_API_KEY")
)

tags <- get_tags(client)$`Projects and Presentations`$`Bike Predict`
repo_url <- "https://github.com/sol-eng/bike_predict"
```


## 1 ETL

### 1.1 Raw Data Refresh

```{r}
guid <- "e1e47cc0-5c31-41bd-a1f4-5729b2ece52e"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-raw-data-refresh", force = TRUE)
set_content_tags(content, tags$R$ETL)
set_image_path(content, "./content/01-etl/01-raw-data-refresh/icon.drawio.png")
```

```{r}
# Pinned station info
guid <- "00036e13-9a3c-44c6-84eb-253de91b10c2"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_content_tags(content, tags$R$ETL)
set_image_path(content, "./img/icon-pins-data.drawio.png")
```

### 1.2 Tidy data

```{r}
guid <- "dccc4f8a-faaf-4700-a74b-076a8d976992"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-tidy-data", force = TRUE)
set_content_tags(content, tags$R$ETL)
set_image_path(content, "./content/01-etl/02-tidy-data/icon.drawio.png")
```

## 2 Model

### 2.1 Train and Deploy Model

```{r}
guid <- "b05369ac-19a7-4dd9-9d9d-95b94906778d"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-train-and-deploy-model", force = TRUE)
set_content_tags(content, tags$R$Model)
set_image_path(content, "./content/02-model/01-train-and-deploy-model/icon.drawio.png")
```

```{r}
# Pinned model
guid <- "0273207f-0f1f-44cb-845e-408f9dae2dd6"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_content_tags(content, tags$R$Model)
set_image_path(content, "./img/icon-pins-model.drawio.png")
```

```{r}
# Deployed API
guid <- "69186bcd-5a1d-4607-a68b-da78ee6cdf2a"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_content_tags(content, tags$R$Model)
set_image_path(content, "./img/icon-plumber.drawio.png")
```

### 2.2 Model Metrics

```{r}
guid <- "0a8562f1-7c92-498f-9987-4481a2ac949c"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-model-metrics", force = TRUE)
set_content_tags(content, tags$R$Model)
set_image_path(content, "./content/02-model/02-model-metrics/icon.drawio.png")
```

## 3 App

### 3.1 Client App

```{r}
guid <- "0477855b-caeb-43e8-b3d9-28e0965e6230"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-client-app", force = TRUE)
set_content_tags(content, tags$R$App)
set_image_path(content, "./content/03-app/01-client-app/icon.drawio.png")
```

### 3.2 Connect Widgets App

```{r}
guid <- "7964dd93-fc83-4d52-8d34-d0840d25996f"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-dashboard", force = TRUE)
set_content_tags(content, tags$R$App)
set_image_path(content, "./content/03-app/02-connect-widgets-app/icon.drawio.png")
```

### 3.3 Client App Dev

```{r}
guid <- "8dfbe6d2-bea7-4554-a509-2c7e4e1baa19"
content <- content_item(client, guid)

# Configure content settings
content$update(access_type = "all")
set_vanity_url(content, "bike-predict-r-client-app-dev", force = TRUE)
set_content_tags(content, tags$R$App)
set_image_path(content, "./content/03-app/03-client-app-dev/icon.drawio.png")
```
