---
title: "Write manifest.json files"
date: "`r Sys.time()`"
output: html_document
---

This purpose of this script is write a manifest.json file for each item of content.

```{r setup}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(rsconnect)
library(quarto)
```

## 1 ETL

### 1.1 Raw Data Refresh

```{r}
writeManifest(
  appDir = "content/01-etl/01-raw-data-refresh", 
  appPrimaryDoc = "document.qmd",
  quarto = quarto_path()
)

print("Complete 🎉")
```

### 1.2 Tidy data

```{r}
writeManifest(
  appDir = "content/01-etl/02-tidy-data", 
  appPrimaryDoc = "document.qmd",
  quarto = quarto_path()
)

print("Complete 🎉")
```

## 2 Model

### 2.1 Train and Deploy Model

```{r}
writeManifest(
  appDir = "content/02-model/01-train-and-deploy-model", 
  appPrimaryDoc = "document.qmd",
  quarto = quarto_path()
)

print("Complete 🎉")
```

### 2.2 Model Metrics

```{r}
writeManifest(
  appDir = "content/02-model/02-model-metrics", 
  appPrimaryDoc = "document.qmd",
  quarto = quarto_path()
)

print("Complete 🎉")
```

## 3 App

### 3.1 Client App

```{r}
writeManifest(
  appDir = "content/03-app/01-client-app", 
  appFiles = "app.R"
)
print("Complete 🎉")
```

### 3.2 Connect Widgets Dashboard

```{r}
writeManifest(
  appDir = "content/03-app/02-connect-widgets-app", 
  appPrimaryDoc = "document.qmd",
  quarto = quarto_path()
)

print("Complete 🎉")
```

### 3.2 Client App Dev

```{r}
writeManifest(
  appDir = "content/03-app/03-client-app-dev", 
  appFiles = c("app.R")
)
print("Complete 🎉")
```
