---
title: "Build Model"
author: "Alex"
date: "`r Sys.time()`"
output: html_document
---

# Load Libraries and connect to board
```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(bikeHelpR)
library(xgboost)
```

# Get data
```{r}
con <- DBI::dbConnect(odbc::odbc(), "Content DB")
rsc <- pins::board_rsconnect(auth = "envvar")
```


# Perform Training Split

```{r}
all_days <- tbl(con, "bike_model_data")
n_days_test <- 2
months_train <- 6

dates <- all_days %>% 
  count(date) %>%
  arrange(desc(date)) %>%
  head(n_days_test + 1) %>%
  pull(date) %>%
  as.Date()

split_date <- dates[n_days_test + 1]
start_train_date <- split_date - dmonths(months_train)

test_dates <- dates[1:n_days_test]
test_dates_str <- paste(test_dates, collapse = " and ")

print(glue::glue(
  "Using data on or before {min(test_dates)} as training, data from {test_dates_str} to test."
))

train_dat <- all_days %>% 
  dplyr::filter(
    date <= split_date, 
    date >= start_train_date
  ) %>% 
  dplyr::collect()

recipe <- recipe(n_bikes ~ ., data = train_dat) %>%
  step_dummy(dow) %>%
  prep(train_dat, retain = FALSE)
```


Make recipe for model:

```{r}
# downsample if working interactively
if (interactive()) {
  train_dat <- dplyr::sample_frac(train_dat, 0.5)
}

train_mat <- recipe %>%
  bake(train_dat)
```

# Train and Save Model

```{r train_mod}
mod <- parsnip::xgb_train(
  train_mat %>% select(-n_bikes, -id, -date), 
  train_mat %>% pull(n_bikes), 
  nrounds = ifelse(interactive(), 50, 500)
)
```
# Brief model evaluation

```{r eval_mod}
test_date_start <- min(test_dates)
test_dat <- all_days %>% 
  filter(date >= test_date_start) %>% 
  collect()

preds <- bake(recipe, test_dat) %>%
  select(-n_bikes, -id, -date) %>% 
  as.matrix() %>% 
  predict(mod, .)

results <- test_dat %>% 
  mutate(preds = preds)

oos_metrics(results$n_bikes, results$preds)
```

# Save model as pin with some metadata

```{r pin_mod}
model_details <- list(
     model = mod,
     train_date = today(),
     train_window_start = start_train_date,
     split_date = split_date, 
     recipe = recipe
)

pins::pin_write(board = rsc,
  x = model_details, 
  name = "bike_model_rxgb", 
  description = "Model of Capitol Citybikes Available per Station",
  type = "rds", 
  access_type = "all"
  )
```

```{r}
DBI::dbDisconnect(con)
```
