---
title: "ETL Step 2 - Write station data to pin"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(dplyr)
library(glue)

# The following packages are not directly called, but are requirements. They
# need to be here so that `rsconnect::writeManifest` is able to capture them
# as a dependency.
library(dbplyr)
library(purrr)
```

## Get station data from API

Get the latest station data from <https://capitalbikeshare.com> API.

```{r get_station_data}
# The station information endpoint.
station_information_url <- 
  bikeHelpR::feeds_urls() %>% 
  filter(name == "station_information") %>% 
  pull(url)

# Call the endpoint to obtain the JSON data.
request <- httr2::request(station_information_url)
response <- httr2::req_perform(request)
json_data <- httr2::resp_body_json(response)

# Convert the JSON data into a tibble.
station_info <- 
  json_data$data %>%
  as_tibble() %>%
  tidyr::unnest_wider(stations) %>%
  select(station_id, name, lat, lon) %>%
  distinct() %>%
  mutate(
    last_updated = as.POSIXct(
      json_data$last_updated,
      origin = "1970-01-01 00:00:00 UTC"
    )
  )

glimpse(station_info)
```

## Publish data to pin

Publish the station info data to a pin on RStudio Connect.

```{r pin_to_connect}
# Connect to a board.
board <- pins::board_rsconnect(server = "https://colorado.rstudio.com/rsc")

# Post the data tot he board.
board |> 
  pins::pin_write(
    station_info,
    name = "bike-predict-r-station-info-pinned",
    title = "Bike Predict (R) - ETL - Station Info Pin",
    versioned = TRUE,
    description = glue("Bike station data from endpoint {station_information_url}")
  )
```

Update the content metadata on Connect.

```{r connect_config}
# Set content permissions
client <- connectapi::connect(
  server = Sys.getenv("CONNECT_SERVER"),
  api_key = Sys.getenv("CONNECT_API_KEY")
)

# Get the content
content <-client %>%
  connectapi::content_item("0b0b29ef-9e00-48f8-a821-053e68cacfdb")

# Make the app visible to the world!
  content$update(access_type = "all")
  
  # Define the contents collaborators
  collaborators <- c(
    "69db516b-ba3e-442a-84d9-f916fc92a2ca", # Gagan Singh
    "99a43fac-2edd-4c31-8cba-a001c507da2e"  # Xu Fei
    
  )
  for (c in collaborators) {
    content %>%
      connectapi::content_add_user(c, role = "owner")
  }
  # Get tags.
  tags <- client %>%
    connectapi::get_tags()
  
  # Update content settings.
  content %>%
    connectapi::set_content_tags(tags$`Projects and Presentations`$`Bike Predict`$R$ETL) %>%
    connectapi::set_image_path("../../../img/bike_share_connect_image.drawio.png") %>%
    connectapi::set_vanity_url("bike-predict-r-station-info-data-pin")
```
