---
title: "Create Training Data"
author: "Alex Gold"
date: "`r Sys.time()`"
output: html_document
---

```{r}
library(dplyr)
library(dbplyr)
library(bikeHelpR)
library(recipes)
library(lubridate)
```

```{r}
con <- DBI::dbConnect(odbc::odbc(), "Content DB")
df <- tbl(con, "bike_model_data")
pins::board_register_rsconnect(
  server = "https://colorado.rstudio.com/rsc",
  key = Sys.getenv("RSTUDIOCONNECT_API_KEY")
)
```

```{r}
n_days_test <- 2
months_train <- 6
dates <- df %>% 
  count(date) %>%
  arrange(desc(date)) %>%
  head(n_days_test + 1) %>%
  pull(date) %>%
  as.Date()

split_date <- dates[n_days_test + 1]
start_train_date <- split_date %m-% months(months_train)

test_dates <- dates[1:(length(dates) - 1)]
test_dates_str <- paste(test_dates, collapse = " and ")

print(glue::glue(
  "Using data on or before {min(test_dates)} as training, data from {test_dates_str} to test."
))
```

```{r}
print(glue::glue("Using data between {start_train_date} and {split_date} for training."))

train_dat <- df %>% 
  dplyr::filter(
    date <= split_date, 
    date >= start_train_date
  ) %>% 
  dplyr::collect()

recipe <- recipe(n_bikes ~ ., data = train_dat) %>%
  step_dummy(dow) %>%
  prep(train_dat, retain = FALSE)
```

```{r}
pins::pin(
  list(
    train_date = Sys.Date(), 
    split_date = split_date, 
    train_start = start_train_date,
    recipe = recipe), 
  "bike_model_params", "Parameters for Creating Training Dataset", 
  board = "rsconnect"
)
```

