---
title: "Clean Analysis Dataset"
author: "Alex"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up packages and connect to RStudio Connect board
```{r}
library(tidyverse)
library(odbc)

con <- dbConnect(odbc::odbc(), "Content DB", timeout = 10)
pins::board_register_rsconnect(server = "https://colorado.rstudio.com/rsc",
                               key = Sys.getenv("RSTUDIOCONNECT_API_KEY"))
```

# Connect to Database Data
```{r, download}
DBI::dbWriteTable(con, "bike_station_info", pins::pin_get("alex.gold/bike_station_info"), overwrite = TRUE)

df_con <- dplyr::tbl(con, "bike_raw_data")
stats <- dplyr::tbl(con, "bike_station_info")
```

# Clean data
```{r}
db_drop_table(con, "bike_model_data", force = TRUE)
query <- df_con %>% 
    group_by(
        id = station_id, 
        hour = hour(time), 
        date = date(time), 
        month = month(time), 
        dow = TRIM(to_char(time, "Day"))
    ) %>%
    summarize(
        n_bikes = mean(num_bikes_available, na.rm = TRUE)
    ) %>%
    inner_join(
        select(stats, id = station_id, lat, lon)
    ) %>%
    dbplyr::sql_render() %>%
    stringr::str_replace("SELECT", "CREATE TABLE bike_model_data AS SELECT")
dbSendQuery(con, query)
tbl(con, "bike_model_data")
```

```{r}
dbDisconnect(con)
```
