---
title: "Clean Analysis Dataset"
author: "Alex"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up packages and connect to RStudio Connect board
```{r}
library(tidyverse)

pins::board_register("rsconnect", 
                     server = "https://colorado.rstudio.com/rsc/",
                     key = Sys.getenv("RSTUDIOCONNECT_API_KEY"))
con <- dbConnect(odbc::odbc(), "Content DB", timeout = 10)
```

# Connect to Database Data
```{r, download}
df <- tbl(con, "bike_raw_data")
```

# Clean data
```{r}
(df <- df %>% 
   transmute(id = station_id, 
             hour = hour(time), 
             n_bikes = num_bikes_available) %>%
   collect())
```

# Add location data
```{r}
stat <- pins::pin_get("alex.gold/bike_station_info")

(df <- df %>%
    left_join(select(stat, id = station_id, lat, lon)))
```

# Pin
```{r}
pins::pin(df, 
          "bike_model_data", 
          "Capitol bikeshare station status data", 
          board = 'rsconnect')
```
