---
title: "Bike Data Ingest"
author: "Alex"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up packages and connect to RStudio Connect board
```{r}
library(tidyverse)
library(magrittr)
library(dplyr)

source("helper_funcs.R")
pins::board_register("rsconnect", 
                     server = "https://colorado.rstudio.com/rsc/",
                     key = Sys.getenv("RSTUDIOCONNECT_API_KEY"))
```

# Download updated data
```{r, download}
feeds <- httr::GET("https://gbfs.capitalbikeshare.com/gbfs/gbfs.json") %>%
  httr::content() %>%
  clean_feeds()
```

```{r}
# Get station status Data
dat <- get_data("station_status", feeds)

# Remove useless column
df <- dat$data %>%
  select(-eightd_active_station_services)
df$time <- dat$last_updated

df
```

# Combine old and new raw data
```{r}
(old <- pins::pin_get("alex.gold/bike_raw_data", board = 'rsconnect')) 

# Combine old and new data and pin
bind_rows(old, df) %>%
  pins::pin("bike_raw_data", 
            "Raw data for predicting bike availability", 
            "rsconnect")
```

# Clean data
```{r}
df <- df %>% 
  transmute(
    id = as.numeric(station_id), 
    hour = as.numeric(lubridate::hour(time)), 
    n_bikes = as.numeric(num_bikes_available))
```

# Pin
```{r}
pins::pin(df, "bike_model_data", 
          "Capitol bikeshare station status data", 
          board = 'rsconnect')
```
